// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtqPEqU7_B0KDvt2XaXRq9ALHR0SDUSRw',
    appId: '1:806387532823:web:e35b0e85a961e710448852',
    messagingSenderId: '806387532823',
    projectId: 'e-commerce-graduationapp',
    authDomain: 'e-commerce-graduationapp.firebaseapp.com',
    storageBucket: 'e-commerce-graduationapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8NMswXIjJyN2oO4jCJ1_4F7f-i7wcF4',
    appId: '1:806387532823:android:3f452c3a24995c5e448852',
    messagingSenderId: '806387532823',
    projectId: 'e-commerce-graduationapp',
    storageBucket: 'e-commerce-graduationapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB-wH67ZmYkPI4NuxTGLlqttZX5KMJebY',
    appId: '1:806387532823:ios:224f6c45a0d75cb2448852',
    messagingSenderId: '806387532823',
    projectId: 'e-commerce-graduationapp',
    storageBucket: 'e-commerce-graduationapp.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB-wH67ZmYkPI4NuxTGLlqttZX5KMJebY',
    appId: '1:806387532823:ios:224f6c45a0d75cb2448852',
    messagingSenderId: '806387532823',
    projectId: 'e-commerce-graduationapp',
    storageBucket: 'e-commerce-graduationapp.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtqPEqU7_B0KDvt2XaXRq9ALHR0SDUSRw',
    appId: '1:806387532823:web:3f3fc56480f3967c448852',
    messagingSenderId: '806387532823',
    projectId: 'e-commerce-graduationapp',
    authDomain: 'e-commerce-graduationapp.firebaseapp.com',
    storageBucket: 'e-commerce-graduationapp.firebasestorage.app',
  );
}
